### PR TITLE
Updated C wrapper wrt. Torch v1.10

### PR DESCRIPTION
**Pull request by stemann**
Updates the C wrapper based on ocaml-torch @ 0.14 - matching Torch v1.10 (current JLL-build)

Contributes to #54 - follow-up for #56

Notable included changes:
* Updated C wrapper generator based on [ocaml-torch @ 0.14](https://github.com/LaurentMazare/ocaml-torch/tree/a6499811f40282a071179d4306afbbb6023dcc4a/src/gen/gen.ml) - matching Torch v1.10.
* Updated C wrapper (generated part)
* Updated C wrapper (manual part), `torch_api.{cpp, h}`
  * Re-implemented change of return type of functions to status code etc.
* Renamed C wrapper from doeye_caml to torch_c_api
* Restored Julia-specific additions
* Conditional CUDA build - C wrapper can be built without CUDA.
* Added <strike>buildkite steps</strike>GitHub Actions workflow for building C wrapper
* Dev. container: Added support for CUDA and CUDNN

<strike>The last two changes could be moved to a separate PR (to reduce number of changes in this PR).</strike>
 
To-do:
- [x] Clean-up the automatic part (remove comments - fix indentation)
- [x] Adapt the manual part, `torch_api.{cpp, h}`
- [ ] The commit `Changed torch_api.cpp to reduce diff` should be removed before merging: It is meant to reduce the diff when reviewing - it's only a bunch of indentation changes etc. to make the diff smaller.

### CODE REVIEW

**Comment by zsz00** [comment]
What's the status now?

**Comment by stemann** [comment]
It's been a idle for a while, but status is summarised by these comments:
* https://github.com/FluxML/Torch.jl/pull/59#issuecomment-1663745853
* https://github.com/FluxML/Torch.jl/pull/60#issuecomment-1670840261

**Comment by stemann** [comment]
See #54 for status.

**Comment by stemann** [comment]
Yes! :-)

Please give `torch_api.{cpp,h}` a thorough review - I have made some changes in an effort to make things a bit more consistent - e.g. wrt. always returning an int status code.

**Comment by stemann** [comment]
This is the current main diff which covers the hand-written part (`torch_api.{cpp,h}`): https://github.com/FluxML/Torch.jl/compare/7828132d..ece96546

**Comment by stemann** [comment]
The overall aim was to to update for Torch v1.10.2 - but also to make it easier to apply a diff of changes for subsequent version updates...

**Comment by stemann** [comment]
Recap (work in progress):

# General

* Removed argument names from function definitions in `torch_api.h`.
* Definitions in `torch_api.h` were updated to match the implementation in `torch_api.cpp` - e.g. wrt. return value in the first argument, and return code as return value.

# Modified function definitions

```c
int at_float_vec(double *values, int value_len, int type);
```

```c
int at_int_vec(int64_t *values, int value_len, int type);
```

```c
int at_grad_set_enabled(int);
```

```c
int at_int64_value_at_indexes(double *i, tensor, int *indexes, int indexes_len);
```

```c
tensor at_load(char *filename);
```

```c
int ato_adam(optimizer *, double learning_rate,
                   double beta1,
                   double beta2,
                   double weight_decay);
```

```c
int atm_load(char *, module *);
```

# Added function definitions

* int at_is_sparse(int *, tensor)
* int at_device(int *, tensor)

* int at_stride(tensor, int *)

* int at_autocast_clear_cache();
* int at_autocast_decrement_nesting(int *);
* int at_autocast_increment_nesting(int *);
* int at_autocast_is_enabled(int *);
* int at_autocast_set_enabled(int *, int b);

* int at_to_string(char **, tensor, int line_size)

* int at_get_num_threads(int *);
* int at_set_num_threads(int n_threads);

* int ati_none(ivalue *);
* int ati_bool(ivalue *, int);
* int ati_string(ivalue *, char *);
 * int ati_tuple(ivalue *, ivalue *, int);
* int ati_generic_list(ivalue *, ivalue *, int);
* int ati_generic_dict(ivalue *, ivalue *, int);
* int ati_int_list(ivalue *, int64_t *, int);
* int ati_double_list(ivalue *, double *, int);
* int ati_bool_list(ivalue *, char *, int);
* int ati_string_list(ivalue *, char **, int);
* int ati_tensor_list(ivalue *, tensor *, int);

* int ati_to_string(char **, ivalue);
* int ati_to_bool(int *, ivalue);
* int ati_length(int *, ivalue);
* int ati_to_generic_list(ivalue, ivalue *, int);
* int ati_to_generic_dict(ivalue, ivalue *, int);
* int ati_to_int_list(ivalue, int64_t *, int);
* int ati_to_double_list(ivalue, double *, int);
* int ati_to_bool_list(ivalue, char *, int);
* int ati_to_tensor_list(ivalue, tensor *, int);

**Comment by stemann** [comment]
@DhairyaLGandhi Do you if anyone is available for reviewing these changes?

**Review by ToucheSir — APPROVED** [review]

**Pull request merged**
